### PR TITLE
Update git ignore (test of github pull request)

### PR DESCRIPTION
**Pull request by fordp2002**
Trivial change to test pull request.

### CODE REVIEW

**Comment by ThomasAdam** [comment]
Thanks.  Can you please ensure you keep the file sorted, please?  I've found that to be very handy for this file, in particular.

**Comment by fordp2002** [comment]
Well I added the ignore from the SourceTree gui. I will go in and edit it in future I prefer the execeptions stored under a heading too.

**Comment by fordp2002** [comment]
I have added a heading now

**Comment by fordp2002** [comment]
Yes I should have said Visual Studio 2013 Community Edition. I have already said I would also build using the open source toolchain if I had the instructions. I already started two wiki entries. I may even try BSD for the hell of it I have so many spare PCs lying about ;)

**Comment by ThomasAdam** [comment]
What's happening with this pull-request?  If anything?

**Comment by fordp2002** [comment]
Sorry I have been away. I will try and get some time to get B-Em building on Visual Studio. The only change I was proposing was Visual Studio exclusions. I am still not clear how to handle line endings at the moment, I will get to the bottom of that at some point.

**Comment by SteveFosdick** [comment]
With regard to the line endings, the git repository uses LF only, i.e. the Unix convention.

Although many Windows programs only work with the Windows CR,LF convention editors for programmers can usually handle Unix format and maybe MAC (and Acorn) format too (CR-only) so maybe Visual Studio will too.  Even so I think there are some git options to set here - see https://git-scm.com/docs/gitattributes - to have line endings normalised as files are committed because I am sure, even if Visual Studio can handle Unix line endings, for new files it is bound to use the Windows convention and then we end up with a mixed bag.

**Comment by hoglet67** [comment]
@SteveFosdick -- don't we actually already enable the git auto line ending magic?
https://github.com/stardot/b-em/blob/master/.gitattributes

@fordp2002 -- if you clone the repository on Windows, then any "text" fines should be converted to crlf endings. Then when you check back in, they are converted back again. At least, that's how I think it's meant to work....

**Comment by fordp2002** [comment]
Converting is one way of working. The other is just to use Unix line endings on Windows which is the way I would prefer to work as I think it is best practice. Visual Studio is happy with Unix Line Endings even if notepad is not! However automatically created files have to configured to retain there settings.

**Pull request closed without merging**
