### PR TITLE
vsprojx fix for 32016 and a debugger bugfix

### PR DESCRIPTION
**Pull request by dominicbeesley**
A define was missing for the 32016 and I spotted that the debugger if given an address >&FFFF was crashing

Not sure how to easily split this into two pull requests!

D

### CODE REVIEW

**Comment by fordp2002** [comment]
I prefer the constant 0x10000 to 65536. Possibly better to change the code so you can use 0xFFFF which has even more meaning.

**Comment by dominicbeesley** [comment]
> I prefer the constant 0x10000 to 65536. Possibly better to change the code so you can use 0xFFFF which has even more meaning.

I wasn't sure, so I followed the style where the arrays are defined in 6502.h and elsewhere in the code.

**Comment by fordp2002** [comment]
No problem, just a personal preference.

**Comment by dominicbeesley** [comment]
Ah, hang on probably better hold off on this and I'll have a more in-depth look in the morning, there's other stuff that fails when address is > &FFFF. I'll come up with a better fix tomorrow.

Would it be better to just make read/writemem take a uint16_t? If not then what should the default out of bounds value be 0xFF, high 8 bits of address?

D

**Comment by dominicbeesley** [comment]
I've now updated this pull to just ignore reads/writes above 64k which seems safe and logical

**Review by SteveFosdick — COMMENTED** [review]
This latest version looks fine.  To answer the question about maybe using a unit16_t for the address, the reason it's uint32_t is because they debugger is intended to be useful for all the processors and there is a set of these functions for the various processors that must all use the same calling convention.

**Review by SteveFosdick — CHANGES_REQUESTED** [review]
The only barrier I can see to merging this is that github says there are merge conflicts for the MS Visual C++ changes.  As that's your area of expertise and not mine it would be better you resolve them than if I try to do so.

**Comment by dominicbeesley** [comment]
Thanks Steve,

I've done the resolve conflicts, should be good to go

D

**Review by SteveFosdick — APPROVED** [review]

**Pull request merged**
